// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-FDfe-0u_5CTmNzwz6Eps9bmMnunY1Yc',
    appId: '1:121758559763:web:549c770776b360b6aa99e6',
    messagingSenderId: '121758559763',
    projectId: 'fir-project-1-a1f1e',
    authDomain: 'fir-project-1-a1f1e.firebaseapp.com',
    storageBucket: 'fir-project-1-a1f1e.firebasestorage.app',
    measurementId: 'G-M1ERP098DW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjCpi8xvrAvdt8q7AYPkkidZvKULGjYcU',
    appId: '1:121758559763:android:4691ce03d814b843aa99e6',
    messagingSenderId: '121758559763',
    projectId: 'fir-project-1-a1f1e',
    storageBucket: 'fir-project-1-a1f1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQijoF9mzCc4BGnejnC2Q_JIUmrkXFRgU',
    appId: '1:121758559763:ios:5f42d6a48f820b71aa99e6',
    messagingSenderId: '121758559763',
    projectId: 'fir-project-1-a1f1e',
    storageBucket: 'fir-project-1-a1f1e.firebasestorage.app',
    iosBundleId: 'com.example.tripbudgeter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQijoF9mzCc4BGnejnC2Q_JIUmrkXFRgU',
    appId: '1:121758559763:ios:5f42d6a48f820b71aa99e6',
    messagingSenderId: '121758559763',
    projectId: 'fir-project-1-a1f1e',
    storageBucket: 'fir-project-1-a1f1e.firebasestorage.app',
    iosBundleId: 'com.example.tripbudgeter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-FDfe-0u_5CTmNzwz6Eps9bmMnunY1Yc',
    appId: '1:121758559763:web:8b7d04cdf892cc0daa99e6',
    messagingSenderId: '121758559763',
    projectId: 'fir-project-1-a1f1e',
    authDomain: 'fir-project-1-a1f1e.firebaseapp.com',
    storageBucket: 'fir-project-1-a1f1e.firebasestorage.app',
    measurementId: 'G-ZYYN19M17Y',
  );
}
